name: Checkout Code Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       #checkout Code
      - name: Checkout code
        uses: actions/checkout@v3
        
       # Check Code is chechout or not
      - name: List files
        run: ls -al
        
      # Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Step 3: Build optimized Docker image with multi-stage build
      - name: Build Docker image
        run: |
          docker build --file Dockerfile --tag my-app-image:latest .

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1    
